/* PRIMEIRO PROCEDIMENTO PLSQL */

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE NOTAS
    IS
    NOTA1       NUMBER;
    NOTA2       NUMBER;
    NOTA3       NUMBER;
    RESULTADO   NUMBER;
    SOMA        NUMBER;
    MEDIA       NUMBER;
    NOME        VARCHAR(50);
BEGIN
    
    NOME    := 'Wesley Sartori';
    NOTA1   := 0;
    NOTA2   := 2;
    NOTA3   := 5;
    SOMA := (NOTA1 + NOTA2 + NOTA3);
    MEDIA := SOMA / 3;
    
    IF MEDIA >= 7 AND MEDIA < 10 THEN
        DBMS_OUTPUT.PUT_LINE('ALUNO APROVADO.' || (MEDIA));        
    ELSIF MEDIA = 10 THEN
        DBMS_OUTPUT.PUT_LINE('ALUNO EXCELENTE.' || (MEDIA));            
    ELSE 
        DBMS_OUTPUT.PUT_LINE('ALUNO REPROVADO.' || (MEDIA));    
    END IF;
    DBMS_OUTPUT.PUT_LINE('A SOMA DAS NOTAS É ' || (SOMA));
    DBMS_OUTPUT.PUT_LINE('A MÉDIA DAS NOTAS É ' || (MEDIA));    
END;

EXECUTE NOTAS;