/* PRIMEIRO BLOCO ANONIMO PL/SQL*/

SET SERVEROUTPUT ON;

DECLARE 

NUMERO1 NUMBER;
NUMERO2 NUMBER;

BEGIN
    NUMERO1 := 2;
    NUMERO2 := 3;
    
    DBMS_OUTPUT.PUT_LINE('A SOMA É ' || (NUMERO1 + NUMERO2));
END;