/* PRIMEIRO PROCEDIMENTO PLSQL */

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE QUAL_MES
    IS
    QUAL_MES NUMBER;
    NOME_MES VARCHAR2(15);
BEGIN
    QUAL_MES := 12;
    CASE 
        WHEN QUAL_MES = 1  THEN NOME_MES   := 'JANEIRO';
        WHEN QUAL_MES = 2  THEN NOME_MES   := 'FEVEREIRO';
        WHEN QUAL_MES = 3  THEN NOME_MES   := 'MARÇO';
        WHEN QUAL_MES = 4  THEN NOME_MES   := 'ABRIL';
        WHEN QUAL_MES = 5  THEN NOME_MES   := 'MAIO';
        WHEN QUAL_MES = 6  THEN NOME_MES   := 'JUNHO';
        WHEN QUAL_MES = 7  THEN NOME_MES   := 'JULHO';
        WHEN QUAL_MES = 8  THEN NOME_MES   := 'AGOSTO';
        WHEN QUAL_MES = 9  THEN NOME_MES   := 'SETEMBRO';
        WHEN QUAL_MES = 10 THEN NOME_MES   := 'OUTUBRO';
        WHEN QUAL_MES = 11 THEN NOME_MES   := 'NOVEMBRO';
        WHEN QUAL_MES = 12 THEN NOME_MES   := 'DEZEMBRO';
    END CASE;
    DBMS_OUTPUT.PUT_LINE(NOME_MES);    
END;

EXECUTE QUAL_MES;